/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ashokk' at '6/16/16 5:51 PM' with Gradle 2.7
 *
 * @author ashokk, @date 6/16/16 5:51 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
