/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ashokk' at '5/31/16 2:33 PM' with Gradle 2.7
 *
 * @author ashokk, @date 5/31/16 2:33 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
