/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ashokk' at '6/3/16 6:46 PM' with Gradle 2.7
 *
 * @author ashokk, @date 6/3/16 6:46 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
