/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'ashokk' at '6/16/16 5:51 PM' with Gradle 2.7
 *
 * @author ashokk, @date 6/16/16 5:51 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
